feat: add support for multiple arguements

diff --git a/scripts/.local/bin/scripts/uploadbook b/scripts/.local/bin/scripts/uploadbook
--- a/scripts/.local/bin/scripts/uploadbook
+++ b/scripts/.local/bin/scripts/uploadbook
@@ -2,55 +2,58 @@
 
 # Validate input arguements
 if [ -z "$1" ]; then
-    echo "No book provided to upload!"
-    echo "Usage: uploadbook <name_of_book.epub>"
+    echo "No book(s) provided to upload!"
+    echo "Usage: uploadbook <book1.epub|pdf> [book2.epub|pdf] ..."
     exit 1
 fi
 
-BOOK="$1"
 
-# Extract author from metadata
-if [[ "$BOOK" == *.pdf ]]; then
-    AUTHOR=$(pdfinfo "$BOOK" | awk -F': *' '/^Author/ {print $2}')
-elif [[ "$BOOK" == *.epub ]]; then
-    AUTHOR=$(ebook-meta "$BOOK" | awk -F': *' '/^Author/ {print $2}')
-else
-    echo "Unsupported file format!"
-    echo "Please provide a .epub or .pdf file"
-    exit 1
-fi
-
-# If there's an author in [brackets], use that instead of the all the other authors
-if [[ "$AUTHOR" == *"["*"]"* ]]; then
-  # take text between the first '[' and the next ']'
-  AUTHOR="${AUTHOR#*[}"      # strip up to first '[' (inclusive)
-  AUTHOR="${AUTHOR%%]*}"     # strip from first ']' to end (inclusive)
-fi
-
-# if "Last, First", swap to "First Last" and drop the comma
-if [[ "$AUTHOR" == *,* ]]; then
-    last="${AUTHOR%%,*}"
-    first="${AUTHOR#*,}"
-    AUTHOR="$first $last"
-    AUTHOR="${AUTHOR:1}" # remove first character which is usually a space
-fi
-
-# if author is 'unknown', let user manually create there own author
-if [[ "${AUTHOR,,}" == "unknown" ]]; then
+for BOOK in "$@"; do
     echo
-    read -p "Author is 'Unknown', are you sure this is correct? (y/n): " answer
-    if [[ "${answer,,}" == 'y' ]]; then
-        echo "Proceeding..."
+    echo "UPLOADING: $BOOK..."
+    echo
+
+    # Extract author from metadata
+    if [[ "$BOOK" == *.pdf ]]; then
+        AUTHOR=$(pdfinfo "$BOOK" | awk -F': *' '/^Author/ {print $2}')
+    elif [[ "$BOOK" == *.epub ]]; then
+        AUTHOR=$(ebook-meta "$BOOK" | awk -F': *' '/^Author/ {print $2}')
     else
-        read -p "What is the author of this book?: " new_author
-        AUTHOR="$new_author"
+        echo "Unsupported file format!"
+        echo "Please provide a .epub or .pdf file"
+        exit 1
     fi
-fi
 
-echo "Using author: $AUTHOR"
+    # If there's an author in [brackets], use that instead of the all the other authors
+    if [[ "$AUTHOR" == *"["*"]"* ]]; then
+    # take text between the first '[' and the next ']'
+    AUTHOR="${AUTHOR#*[}"      # strip up to first '[' (inclusive)
+    AUTHOR="${AUTHOR%%]*}"     # strip from first ']' to end (inclusive)
+    fi
 
-# Check if author folder already exists
-ssh tuxtower "bash -s -- $(printf '%q' "$AUTHOR")" <<'REMOTE'
+    # if "Last, First", swap to "First Last" and drop the comma
+    if [[ "$AUTHOR" == *,* ]]; then
+        last="${AUTHOR%%,*}"
+        first="${AUTHOR#*,}"
+        AUTHOR="$first $last"
+        AUTHOR="${AUTHOR:1}" # remove first character which is usually a space
+    fi
+
+    # if author is 'unknown', let user manually create there own author
+    if [[ "${AUTHOR,,}" == "unknown" ]]; then
+        read -p "Author is 'Unknown', are you sure this is correct? (y/n): " answer
+        if [[ "${answer,,}" == 'y' ]]; then
+            echo "Proceeding..."
+        else
+            read -p "What is the author of this book?: " new_author
+            AUTHOR="$new_author"
+        fi
+    fi
+
+    echo "Using author: $AUTHOR"
+
+    # Check if author folder already exists
+    ssh tuxtower "bash -s -- $(printf '%q' "$AUTHOR")" <<'REMOTE'
 dir="$HOME/testbooks/$1"
 if [ -d "$dir" ]; then
     echo
@@ -64,17 +67,18 @@ else
 fi
 REMOTE
 
-echo
-
-# Copy book to author folder
-echo "Copying book to Calibre..."
-echo 
-
-if scp "$BOOK" "tuxtower:~/testbooks/$AUTHOR/"; then
     echo
-    echo "Successfully uploaded book"
-else
-    echo
-    echo "Error: Failed to upload book!"
-    exit 1
-fi
+
+    # Copy book to author folder
+    echo "Copying book to Calibre..."
+    echo 
+
+    if scp "$BOOK" "tuxtower:~/testbooks/$AUTHOR/"; then
+        echo
+        echo "Successfully uploaded $BOOK"
+    else
+        echo
+        echo "Error: Failed to upload book!"
+        exit 1
+    fi
+done
